// examples/react-boilerplate/src/App.js
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <h1>Vishnu</h1>
        <a
          className="App-link"
          href="https://vishnucss.github.io/vishnu"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Vishnu
        </a>
      </header>
    </div>
  );
}

export default App;

// examples/svelte-boilerplate/src/App.svelte
<script>
	export let name;
</script>

<main class="flex center full-screen text-center">
 <img alt="Vue logo" src="/logo.png" height="165">
  <h1>{name}</h1>
  <a
    href="https://vishnucss.github.io/vishnu"
    target="_blank"
    rel="noopener noreferrer"
  >
    Learn Vishnu
  </a>
</main>

<style>
  a {
    color: var(--primary-color);
  }
</style>
