// examples/vue-boilerplate/src/App.vue
<template>
  <div id="app" class="flex center full-screen">
    <img alt="Vue logo" src="./assets/logo.png" height="165">
    <h1>Vishnu</h1>
    <a
      href="https://vishnucss.github.io/vishnu"
      target="_blank"
      rel="noopener noreferrer"
    >
      Learn Vishnu
    </a>
  </div>
</template>

<script>

export default {
  name: 'App',
}
</script>

<style>
#app {
  font-family: Inter, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
#app h1 {
  font-size: 62px;
  font-weight: 600;
  margin-top: 10px;
}
</style>

// examples/svelte-boilerplate/src/App.svelte
<script>
	export let name;
</script>

<main class="flex center full-screen text-center">
 <img alt="Vue logo" src="/logo.png" height="165">
  <h1>{name}</h1>
  <a
    href="https://vishnucss.github.io/vishnu"
    target="_blank"
    rel="noopener noreferrer"
  >
    Learn Vishnu
  </a>
</main>

<style>
  a {
    color: var(--primary-color);
  }
</style>
